import type { Metadata } from 'next'
import { PageFooter } from '@/components/page-footer'
import { PageHeader } from '@/components/page-header'
import { ThemeProvider } from '@/components/theme-provider'
import { fontMono, fontSans } from '@/lib/font'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  readonly children: React.ReactNode
}

export default function RootLayout({
  children,
}: RootLayoutProps): React.ReactElement {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable}`}
      suppressHydrationWarning
    >
      <body className="font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative grid min-h-screen-dvh grid-rows-[var(--header-height)_1fr] bg-background">
            <PageHeader />
            {children}
            <PageFooter />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
