export const projects = [
  {
    id: 1,
    name: 'E-commerce Platform',
    description: 'Scalable solution with real-time inventory.',
    technologies: ['React', 'Node.js', 'MongoDB'],
    link: '/projects/e-commerce',
  },
  {
    id: 2,
    name: 'Task Manager',
    description: 'Collaborative tracking with analytics.',
    technologies: ['Vue.js', 'Firebase', 'Chart.js'],
    link: '/projects/task-manager',
  },
  {
    id: 3,
    name: 'Social Dashboard',
    description: 'Centralized social media management.',
    technologies: ['Angular', 'Node.js', 'PostgreSQL'],
    link: '/projects/social-dashboard',
  },
  {
    id: 4,
    name: 'Fitness App',
    description: 'Mobile-first workout and nutrition tracker.',
    technologies: ['React Native', 'Python', 'AWS'],
    link: '/projects/fitness-app',
  },
  {
    id: 5,
    name: 'Custom CMS',
    description: 'Content system with SEO tools.',
    technologies: ['Next.js', 'GraphQL', 'Prisma'],
    link: '/projects/cms',
  },
  {
    id: 6,
    name: 'Chat Application',
    description: 'Real-time messaging with end-to-end encryption.',
    technologies: ['Socket.io', 'Express', 'MongoDB'],
    link: '/projects/chat-app',
  },
  {
    id: 7,
    name: 'Portfolio Generator',
    description: 'Automated portfolio creation tool.',
    technologies: ['React', 'Node.js', 'AWS Lambda'],
    link: '/projects/portfolio-generator',
  },
  {
    id: 8,
    name: 'Weather Forecast',
    description: 'Location-based weather predictions.',
    technologies: ['React', 'Node.js', 'OpenWeatherAPI'],
    link: '/projects/weather-forecast',
  },
  {
    id: 9,
    name: 'Job Board',
    description: 'Niche job listing and application platform.',
    technologies: ['Vue.js', 'Express', 'MongoDB'],
    link: '/projects/job-board',
  },
  {
    id: 10,
    name: 'Recipe Finder',
    description: 'Personalized recipe recommendations.',
    technologies: ['React', 'Python', 'TensorFlow'],
    link: '/projects/recipe-finder',
  },
];
